welcome_msg = "Welcome. I am a conversational agent and can explain decisions made by machine learning models. Currently, the default dataset is german-credit. Would you like to go on with this dataset? Please type 'yes' to continue, otherwise, type one of the supported dataset in this list [adult, iris, titanic]?"
dataset_error_msg = "I only support adult, iris, titanic and german-credit dataset, please type a correct name"
wait_msg = "Wait a min, I need to learn it"
list_feature_request_msgs = ["How about your ", "What is your ", "Give me your "]
record_info_msg = "I recorded the information {} "
predict_msg = "you have {}"
question_msg = "You can ask my questions about a machine learning learning model, such as: \nWhy was the prediction made? \nWhy was Y not predicted? \nWhat should change in order to make prediction Y? \nPlease type your question."
select_msg = "Sorry, I am not exactly sure whether I understood your question correctly.\nDid you mean any of the below? Please select a number.\n0. Type a new question.\n"
rephrase_question_msg = "Sorry, I don't understand your question. Please rephrase your question."
no_cf_msg = "Sorry, I couldn't find the way to modify {} to change the label"
cant_answer_msg = "I am not capable of answering your question. Questions of this type can currently not be answered by an explainable AI method."
repeat_cat_features = "The input value is not valid, please choose in one of the following values:{}"
repeat_num_features = "The input value is not valid, please type in one of the following values:{}"
request_number_msg = "It is not a number or not an appropiate number. Please choose another number"
request_more_msg = "Here are some example questions. Pick a number to choose one of them or type 0 to enter a new question \n"
ans_shap_question_single_feature = "Here is the impact of this feature. "
l_shap_question_ids = [3, 5, 6, 8, 67, 69]
l_shap_question_feature = [3, 5, 69]
l_shap_question_single_feature = [6]
l_dice_question_ids = [11, 12, 14, 71]
l_dice_question_relation_ids = [71]
l_anchor_question_ids = [20, 15, 13]
l_feature_questions_ids = [6, 12]
l_new_predict_question_ids = [64]
l_questions = ["How about your ", "What is your ", "Give me your "]
l_support_questions_ids = l_shap_question_ids+l_dice_question_ids+l_anchor_question_ids